version: "3.9"

services:
    modcast:
        image: modcast
        container_name: modcast
        volumes:
            - type: bind
              source: /tmp/.X11-unix
              target: /tmp/.X11-unix
        tty: true
        stdin_open: true
