version: "3.9"

services:
    modcast:
        build:
            context: ./
        image: shift-modcast-twitchbot:latest
        container_name: shift-modcast-twitchbot
        volumes:
            - type: bind
              source: /etc/modcast/modcast.json
              target: /etc/modcast/modcast.json
        deploy:
            replicas: 0
            restart_policy:
                condition: on-failure